print(r"                                           ,,   ,,                                                     ")
print(r"`7MM\"\"\"YMM                                 db   db    .g8\"\"\"bgd                                  mm    ")
print(r"  MM    `7                                          .dP'     `M                                  MM    ")
print(r"  MM   d    `7MMpMMMb.pMMMb.   ,pW\"Wq.   `7MM `7MM  dM'       ` `7Mb,od8 `7M'   `MF'`7MMpdMAo. mmMMmm  ")
print(r"  MMmmMM      MM    MM    MM  6W'   `Wb    MM   MM  MM            MM' \"'   VA   ,V    MM   `Wb   MM    ")
print(r"  MM   Y  ,   MM    MM    MM  8M     M8    MM   MM  MM.           MM        VA ,V     MM    M8   MM    ")
print(r"  MM     ,M   MM    MM    MM  YA.   ,A9    MM   MM  `Mb.     ,'   MM         VVV      MM   ,AP   MM    ")
print(r".JMMmmmmMMM .JMML  JMML  JMML. `Ybmd9'     MM .JMML.  `\"bmmmd'  .JMML.       ,V       MMbmmd'    `Mbmo ")
print(r"                                        QO MP                               ,V        MM               ")
print(r"                                        `bmP                             OOb\"       .JMML.             ")